- name: 'Installing Software'
  apt: pkg={{ item }} state=installed
  with_items:
  - apache2
  - libapache2-mod-php5
  - php5-sqlite
  - sqlite

- name: 'Some Symlinks'
  file: src=/opt/nbblog/{{ item }} dest=/var/www/{{ item }} state=link
  with_items:
  - src
  - vendor

- name: 'docroot writeable'
  file: path=/var/www/html state=directory owner=root group=www-data mode=0775

- name: 'remove index.html'
  file: path=/var/www/html/index.html state=absent

- name: 'Enabeling mod_rewrite'
  shell: a2enmod rewrite && service apache2 restart

- name: 'Copying Apache Config'
  copy: src=../files/apache.config dest=/etc/apache2/conf-available/app.conf

- name: 'Enabeling Apache Config'
  shell: a2enconf app && service apache2 restart
